# Generated by Django 4.2.10 on 2024-03-08 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_faqs_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(default='aa', max_length=255),
        ),
    ]
