# Generated by Django 4.2.10 on 2024-03-01 16:11

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_notice_is_popup_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='is_popup_message',
            field=models.BooleanField(choices=[('Yes', 'Yes'), ('No', 'No')], default=False, verbose_name=base.models.PopupMessage),
        ),
    ]
