# Generated by Django 4.2.10 on 2024-03-01 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_notice_is_popup_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='is_popup_message',
        ),
    ]
