# Generated by Django 4.2.10 on 2024-03-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_comment_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='sub_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
