# Generated by Django 4.2.10 on 2024-03-13 12:29

from django.db import migrations
import nepali_datetime_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_vacancy_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='deadline',
            field=nepali_datetime_field.models.NepaliDateField(),
        ),
    ]
