# Generated by Django 4.2.10 on 2024-03-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_calender_calender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar', models.ImageField(upload_to='uploads/calendar')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '00. Calender',
            },
        ),
        migrations.DeleteModel(
            name='Calender',
        ),
    ]
